version: 0.2

env:
  variables:
    SERVERLESS_ACCESS_KEY: "AKNoFnhQONJmCJEZyP93EmhqvWPdj4t6K3317iLVv1W9e"
  variables:
    SNYK_TOKEN: "bb0562b8-7886-425d-b750-7fcfc7ef2199"

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo Installing Serverless Framework...
      - npm install -g serverless
      - echo Installing dependencies...
      - pip install -r requirements.txt
      - echo Installing Snyk...
      - npm install -g snyk
     

  pre_build:
    commands:
      - echo Authenticating with Snyk...
      - snyk auth $SNYK_TOKEN
      - echo Serveless Authentication...
      - export SLS_ACCESS_KEY=$SERVERLESS_ACCESS_KEY
      - echo Running Snyk to check for vulnerabilities...
      - snyk test || { echo "Vulnerabilities found, failing the build"; exit 1; }

  build:
    commands:
      - echo Running serverless deploy...
      - serverless deploy

  post_build:
    commands:
      - echo Deployment is triggered separately.

artifacts:
  files:
    - .serverless/**
  discard-paths: yes
