version: 0.2

env:
  variables:
    SERVERLESS_ACCESS_KEY: "AKrmpljZSj9PwRVkHSNfz9gS27kLiNocBD0SbzxhaesS5"

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo Installing Serverless Framework...
      - npm install -g serverless
      - echo Installing dependencies...
      - pip install -r requirements.txt

  build:
    commands:
      - echo Serverless login.
      - export SLS_ACCESS_KEY=$SERVERLESS_ACCESS_KEY
      - serverless login
      - echo Running serverless deploy...
      - serverless deploy

  post_build:
    commands:
      - echo Deployment is triggered separately.

artifacts:
  files:
    - .serverless/**
  discard-paths: yes