version: 0.2

env:
  variables:
    SERVERLESS_ACCESS_KEY: "AKrmpljZSj9PwRVkHSNfz9gS27kLiNocBD0SbzxhaesS5"
    SNYK_AUTH_TOKEN: "bb0562b8-7886-425d-b750-7fcfc7ef2199"

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo Installing Serverless Framework...
      - npm install -g serverless@3.38.0
      - echo Installing dependencies...
      - pip install -r requirements.txt
      - echo Installing Snyk
      - npm install -g snyk

  pre_build:
    commands:
      - echo Serverless login.
      - export SLS_ACCESS_KEY=$SERVERLESS_ACCESS_KEY
      - echo Snyk authentication
      - snyk auth $SNYK_AUTH_TOKEN
      - serverless plugin install -n serverless-offline
  build:
    commands:
      - echo Setting Serverless access key...
      - export SERVERLESS_ACCESS_KEY=$SERVERLESS_ACCESS_KEY
      - snyk test --file=./requirements.txt || { echo "Vulnerabilities Found, failing the build"; exit 1;}
      - echo Running serverless login...
      - echo Running serverless deploy...
      - serverless deploy

  post_build:
    commands:
      - echo Deployment is triggered separately.

artifacts:
  files:
    - .serverless/**
  discard-paths: yes